name: LoadResourcepackFromServer
version: '1.1.1'
main: top.syshub.loadResourcepackFromServer.LoadResourcepackFromServerPaper
api-version: '1.19'
load: STARTUP
authors: [ Dainsleif ]
description: Have the client download the resource pack directly from the game server.
website: mc.syshub.top
depend: [MESH-Lib]