name: LoadResourcepackFromServer
version: '${mod_version}'
main: top.syshub.loadResourcepackFromServer.LoadResourcepackFromServerPaper
api-version: '${minecraft_version}'
load: STARTUP
authors: [ Dainsleif ]
description: Have the client download the resource pack directly from the game server.
website: mc.syshub.top